services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.prod
    ports:
      - 50052:50052
      - 5002:5002
    depends_on:
      - auth-service-postgres
    networks:
      - auth-service-network
  auth-service-postgres:
    image: postgres:17
    env_file: .env.prod
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth_service_postgres_data:/var/lib/postgresql/data
    networks:
      - auth-service-network

volumes:
  auth_service_postgres_data:

networks:
  auth-service-network:
    driver: bridge